source 'https://rubygems.org'
ruby '2.2.1'
gem 'rails', '4.2.3'
# gem 'mysql2'
gem 'haml'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'redcarpet'
gem 'faker'
gem 'shoppe'
gem 'awesome_print', require:'ap'
gem 'thin'
gem 'pg'

group :development do
  gem 'bullet'
  gem 'better_errors'
  gem 'quiet_assets'
  #gem 'capistrano'
end
